### ISSUE TITLE
timeout=0 will cause poll() to poll forever

### ISSUE THREAD

**Issue by thewhoo** [ddmee/polling2#22]
When the `timeout` argument is set to 0, polling will run forever due to this:
```
timeout = time.time() + timeout if timeout else None
```
evaluating the `timeout` argument to `False`, which in turn sets `timeout` to `None`, which will result in the loop never throwing a `TimeoutException`:

```
if timeout is not None and time.time() >= timeout
```
Is this behavior intentional, especially considering that this works without explicitly setting `poll_forever` to `True`? My assumption was that `timeout=0` would run the target function once and then immediately timeout if `check_success` doesn't pass.

**Comment by ddmee** [comment]
hi @thewhoo, thanks for raising this issue.

I'll have a look now and consider your issue. Yeah, you might well have found a strange corner case, or something that's a bit weird about the API. I'll have a look and see what I can do about it. I'd be slightly worried that someone might be relying on `timeout == 0` to mean `poll_forever=True`. 

Even though, I'd probably think, hmm 'timeout=0' perhaps means yeah timeout immediately and don't even try a single time...

Though, yeah perhaps if `time=0`, try once and then timeout, as you suggest. Maybes that's the best.

I'll have a think about it and see if we can come up with something.

There is the `max_tries` parameter. So if you want to _only_ poll _once_ then `max_tries=1` is probably what you want?

Perhaps we just need to make the documentation clearer, that if timeout is set to 0, this is equivalent to setting `poll_forever=true' ?

**Comment by eugene-bright** [comment]
In my opinion `timeout == 0` or `timeout == None` is quite synonimous to `poll_forever=True` and very convinient in many cases.
I vote to document this behaviour and legitimate it by doing so.

**Comment by eugene-bright** [comment]
Wait, if `timeout == 0` then `poll()` hangs forever regardless of `check_success`. That's definitely not OK
What do you think, @ddmee ?

**Comment by ddmee** [comment]
@eugene-bright 

> Wait, if `timeout == 0` then `poll()` hangs forever regardless of `check_success`. That's definitely not OK
> What do you think, @ddmee ?

@eugene-bright are you sure? I just tried that...

```python
Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from polling2 import poll
>>> poll(target=lambda: True, step=0, timeout=0)
True
>>> 
```

It doesn't look like it's hanging forever.

Yeah I should have updated the documentation to note that `timeout == 0` or `timeout == None` is equivalent to setting `poll_forever=True`. That's basically what the existing behaviour is.

**Comment by eugene-bright** [comment]
> Wait, if `timeout == 0` then `poll()` hangs forever regardless of `check_success`. That's definitely not OK

`check_success` is respected when `timeout == 0`. So `timeout == 0` is synonim of `poll_forever == True`.
All is well, it's just a paranoia.

**Comment by ddmee** [comment]
I'll create a PR now for the documentation.

**Comment by ddmee** [comment]
Opened a PR: https://github.com/ddmee/polling2/pull/25

@eugene-bright or @thewhoo take a look if you want before I merge the PR. (Looks like the travis build pipeline might be broke for some reason, so I'll need to fix that before merging the PR. But it's just a documentation change. So it shouldn't break any of the tests....)
