### ISSUE TITLE
Polling decorator 

### ISSUE THREAD

**Issue by lucasmelin** [ddmee/polling2#26]
Instead of calling the `poll` function directly, it would be nice to be able to decorate a function with an `@poll` decorator instead. A web search yields https://github.com/benjamin-hodgson/poll which was last committed to 6 years ago, but which implemented a polling decorator and could serve as a reference.

**Comment by ddmee** [comment]
Hi @lucasmelin thanks for the idea. I think a polling decorator sounds like a nice idea.

I've given one a go over at https://github.com/ddmee/polling2/pull/27

If you want, take a look and give me any feedback you have. If not, I'm happy with the improvement and I'll merge and release it.

**Comment by lucasmelin** [comment]
I reviewed the PR - the polling decorator looks good, seems like it's exactly what I was looking for. 👍🏻 Thanks for working on this.

**Comment by ddmee** [comment]
cool, merge the change so hopefully it'll do the job.
